export const SESSION_CONSTANTS = {
  AVAILABLE: true,
  START_ROUTE: "/" as string,
  HISTORY_LIMIT: 30,
  POP_CLOSE_MS: 110,
  QUICK_JUMP: ["profile", "projects", "github", "contact", "help"] as const,
  QUICK_JUMP_LABEL: "QUICK JUMP",
  HINT_READY: "Ready. Try commands: profile, projects, skills, contact, whoami",
  HINT_ROUTE_PREFIX: "Ready. Output below from: ",
  PROMPT_PLACEHOLDER: "type a command or press Tab...",
  PROMPT_LABEL: "Command prompt",
  POP_LIST_LABEL: "Command suggestions",
  POP_EMPTY: "no matching commands",
  ERROR_CODE: "exit 127",
  ERROR_SUFFIX: "command not found. type help or / for available commands.",
  NOT_FOUND_TITLE: "404",
} as const;
